### ISSUE TITLE
Stop computing daala-tools metrics

### ISSUE THREAD

**Issue by negge** [xiph/rd_tool#88]
The libvmaf metrics are specified in the AV2 CTC and are already the only ones displayed with BD-rate numbers.

We should just stop computing the daala-tools metrics to save compute.

**Comment by vibhoothi** [comment]
https://github.com/xiph/rd_tool/commit/19387dd6fd9fc21dc111706f7f1e31ec74813364

We stopped computing daala-tools metric with this as showing additional overhead for metrics computation for just counting the number of frames, we moved to count from XML file directly instead.
